### ISSUE TITLE
Money sound not located properly

### ISSUE THREAD

**Issue by Zediax** [Medacorp/Luigi-s-Mansion#106]
**Describe the bug**
The sound of the money (whether it is coins, bills or gems) play below the visual model rather than at the model location.

**To Reproduce**
That discovery was very luck based as I have the "Sound Physics Remaster" mod on, this mod adds reverb and absorption to all sounds that aren't music.

1. Have the Sound Physics Remaster enabled (forge/fabric works)
2. Vaccum some money that is on the floor
3. See bug

**Expected behavior**
Money sound dragged on the floor should be clear to hear and not absorbed, which means the sound comes from below the model where it should come from the model itself.

**Map version:**
3.0.5 (but all may have the same issue i guess)

**Enabled add-ons**
None

**Comment by Dhranios** [comment]
Just to be sure: what sound? bounce, collect, or both?

**Comment by Zediax** [comment]
both
