### ISSUE TITLE
Boolossus Fight

### ISSUE THREAD

**Issue by Zediax** [Medacorp/Luigi-s-Mansion#108]
**Describe the bug**
In the Boolossus fight, when i vaccumed 1 boo the fight ended.

**To Reproduce**
1. Boot up the version 3.0.6 of the map
1. Go to Boolossus
3. Vaccum a Boo

**Expected behavior**
The fight isn't suppose to end right away and the player needs to vaccum all boos in order to end the fight and win.

**Map version:**
3.0.6

**Enabled add-ons**
None

**Additionnal Context**
I sadly wasn't recording as i was just casually showing the map to a friend so there's absolutly no proof of the bug whatsoever.

**Comment by Dhranios** [comment]
I'll investigate. This was supposed to be fixed in 3.0.6, so it it wasn't properly fixed, it'll likely affect 3.1 as well.

**Comment by Zediax** [comment]
it also affected my boo count

**Comment by Dhranios** [comment]
After checking with @Zediax, we found out the map version listed is off by 1, they're using 3.0.5, which pre-dates the fix for this exact issue.
Testing in 3.1 revealed boolossus working fine, aside from a minor visual bug, which got fixed in the latest commit.
