### ISSUE TITLE
Boos can't warp through walls

### ISSUE THREAD

**Issue by orangeisborange** [Medacorp/Luigi-s-Mansion#60]
**Describe the bug**
So, this has happened about 5 or so times now, where the boo will just keep trying to go out the wall but never goes. I left it there with 1 HP seeing if it would go through the wall into the hallway but it never does, it just sits there.

**To Reproduce**
Fight Any boo, this has been happening the entire time since boo release.

**Expected behavior**
Boos should run away and make it to other rooms or hallways essentially escaping Luigi

**Attachments**
![Uploading Screenshot (11).png…]()

**Map version:**
Version 1.5

**Comment by orangeisborange** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/66503790/165497163-d6da0f05-9024-4268-af62-b63cc3cb4c02.png)

For some reason the image didn't upload

**Comment by Dhranios** [comment]
Ok, wow, I really did mess these up; I will probably release a v1.6 to fix this (along with some of the other bugs)
