### ISSUE TITLE
Double use GBH to scan

### ISSUE THREAD

**Issue by orangeisborange** [Medacorp/Luigi-s-Mansion#61]
Not exactly a bug, but in the future would it be possible to make an item that just brings up the scan feature? Would make things a lot easier since there's plenty of times to just pop open the scanner. If not, no worries, figured I'd ask.

**Comment by Dhranios** [comment]
The GBH is intended to be the multi-functional device that E. Gadd explains in the gallery. Yes, in the original scanning, the map and the ghost/item list were all separate buttons, but they were all done on the GBH by luigi (as the visuals indicate). I don't want to add an item for each of those options, nor the portrait battle leave option from the 3DS Remake; that'll just clutter the inventory with seemingly identical looking items.

**Comment by orangeisborange** [comment]
Is there a way to make it a toggle then? Having to click T and stop all forward momentum to open up the scan, and then scan has been a bit weird imo. But, I totally get it if you don't want to clutter the inventory space.

**Comment by Dhranios** [comment]
Hmm, I could make it default selected upon using the GBH when the menu is already opened (so double click being scan)
I'll give this some thought.
