### ISSUE TITLE
Boolosus Perfect Tick Softlock

### ISSUE THREAD

**Issue by Gmanluigi** [Medacorp/Luigi-s-Mansion#66]
Describe the bug
I was facing off against Boolosus, I had my stats up, and as I sucked in the second to last boo, the tick counter for the Boolosus merge started at the same time, and suddenly the last boo was nowhere in sight. I tried to find it only to realize, he had teleported off the arena.

To Reproduce
1. You Can't

Expected behavior
I was expecting the boo to behave like normal.

Map version:
v1.7

Additional context
What have I created? XD

**Comment by Dhranios** [comment]
Fixed in the v1.8 commit.
