### ISSUE TITLE
Twins Room

### ISSUE THREAD

**Issue by Zediax** [Medacorp/Luigi-s-Mansion#74]
The twins room is bugged out: I reached the point where i have to fight the twins to get further on the map, once i accepted to play with them, get out and in of the room and i search a chest nothing happens, when i find them they just go away and i can't do anything else beside exit and reentering the room to search again but nothing still happens

**To Reproduce**
1. Go to The twins room
2. Click on any chest
3. See that nothing happens (may do something since someone on youtube succeded the room)

**Expected behavior**
Twins saying either you cheated to find them or the twins mocking you because you're bad at searching

**Map Version**
Map version 2.2

**Comment by Dhranios** [comment]
Odd, I haven't touched the twins' hide and seek since initial release, and they did work there,and every run I've done since.

couple questions:
1. do you have any add-ons enabled?
2. which mansion do you have this issue in?
3. are you opening the chest with the interact item, or opening it the minecraft way?

**Comment by Zediax** [comment]
1. No i don't have any add-ons available (if optifine is the cuase then it's that)
2. The normal one (the one you have when you just start the game without doing anything)
3. I did both but none worked (i still can try again both ways and tell you after if none worked or not)
4. Nope nothing happens at all when i open a chest except the Twins getting out of the chest when i choose the rights ones

I hope nothing bad is going on here and that i don't have to reset the map entierly thanks for the quick responses :)

**Comment by Dhranios** [comment]
With add-ons I meant the optional data packs shipped with the map.

So if you open the wrong chest, nothing happens; duely noted.
What happens if you only open the right ones (use the poltergust to find the right ones), not a single wrong one? You can reset the mini game be leaving and re-entering.

Resetting the map should never be needed, even for updating, old save data gets converted.

**Comment by Zediax** [comment]
I did find the rights one first try (yeah unbelievable i know) but sadly nothing happened either :(

**Comment by Zediax** [comment]
and no i did not put any datapacks on the map

**Comment by Zediax** [comment]
the thing is that the file is too big ^^' i will have to put it on either Google Drive or Mega

**Comment by Dhranios** [comment]
Please do, and share the link here; I'll tell you when I've downloaded it, so you can remove it then, if you prefer to do so.

**Comment by Zediax** [comment]
https://mega.nz/file/9CE1XKoS#nTQNZzNhqMxSLLskVHQ5U1xOsJhwOJGI6Vtvg2DGHVQ

here i got it quick

**Comment by Dhranios** [comment]
The download seems to get stuck at "737,2 MB/733,7 MB"

**Comment by Dhranios** [comment]
I think I got it; I'll push a single-line fix to this repository; if you could pull the change, or make the same change in your file, you should be able to continue. Please notify me if the fix worked.

If it worked, I'm super surprised why the map functioned fine for me.

**Comment by Zediax** [comment]
so all i need to do i download the line fix and change the file that the line is by the one i'll download ?

**Comment by Dhranios** [comment]
The former, yeah, and tell me if that resolved your issue.

**Comment by Zediax** [comment]
ok i'll do that

**Comment by Zediax** [comment]
it solved it

**Comment by Zediax** [comment]
many thanks to you :D now we solved a good problem

**Comment by Dhranios** [comment]
Alright then, I'll push this (and the biff atlas fix I pushed a bit earlier) to the download then.

Seriously puzzled how only you triggered this.

**Comment by Zediax** [comment]
it solved the doors problem too

**Comment by Dhranios** [comment]
I figured those issues were related/that caused by the other issue.
