### ISSUE TITLE
Being grabbed at same time as reeling in a ghost leaves stray "grabbed" tag, while failing to be grabbed

### ISSUE THREAD

**Issue by Zediax** [Medacorp/Luigi-s-Mansion#75]
**Describe the bug**
You're gonna hate me but my Flashlight just stopped working x) I went to the Mirror Room  next to the Fortune-Telling Room and caught a ghost at the same time another ghost grabbed me and since that, my flashlight don't work anymore

**To Reproduce**
1. Go to the 'Mirror Room'.
2. Catch a ghost at the same time an other ghost grabs you.
3. Flashlight don't work from now on.

**Expected behavior**
Get hit by the ghost or capture the ghost and get grabbed after the capture scene is done

**Map version:**
Still 2.2

https://user-images.githubusercontent.com/112496276/187525198-fbeaf031-83c6-49fd-bde9-114e778bc0ad.mp4

**Comment by Dhranios** [comment]
Do the interact item and gameboy horror still function?
What's the result of the following commands? (use "/gamerule sendCommandFeedback true" first)
/scoreboard players get @s KnockbackType
/tag @s list

**Comment by Zediax** [comment]
the other items work and i'll try that

**Comment by Zediax** [comment]
alright the Knockback type is at 0 and i have the following tags "chance-check", "dark_room", "flashlight_off", flashlight_selected" (since i have the flashlight in my hand this one makes sens), "grabbed", high_health_idle, "idle", "joined", loaded_chunks", "played_opening_music" and "seen-room_name_"

I suppose i have to get rid of the "grabbed" tag ?

**Comment by Dhranios** [comment]
Doesn't simply right clicking the flashlight turn it on again? "flashlight_off" is given when you turn it off by using it only.

"grabbed" should indeed not be present for you, but, looking at the functions, it only interrupts the "always shine" flashlight type.
If you could describe a little bit better what "the same time" is for you (same frame? grabbed, and then latching on to the ghost before getting the struggling animation?) that would help resolve that issue.

**Comment by Zediax** [comment]
right clicking with the flashlight doesn't do anything no

for the grabbing part i'm  not sure if it was the same frame but it was quite close to the exact same time as the ghost with no health left got sucked in the Poltergust

**Comment by Zediax** [comment]
i guess i'll try to remove the tag

**Comment by Zediax** [comment]
okay so the "grabbed" tag was indeed the cause of the problem

**Comment by Zediax** [comment]
it works fine now

**Comment by Zediax** [comment]
i'll try but i can't guarantee that it'll work

**Comment by Dhranios** [comment]
Oh, I think I found it; did the ghost you were vacuuming reach 0HP?

**Comment by Zediax** [comment]
yes it did

**Comment by Dhranios** [comment]
Then the cause is
*drumroll*
Invulnerability frames

The only time you get invulerability, that's not knockback.
1 line fix, again.

**Comment by Zediax** [comment]
i'm good at finding 1 line fixing bugs i see xD

**Comment by Dhranios** [comment]
Hehe, one of the bug reports I recieved a couple months ago was actually a frame-perfect, 50% chance softlock. That was amazing to see having been triggered.

If you run into anything else, do let me know. :)

**Comment by Zediax** [comment]
sure will do (i can't get this one to work tho it's too precise and my game idk why starts too lag as frick)
