### ISSUE TITLE
Game crash can result in forceloaded chunks no longer being forceloaded

### ISSUE THREAD

**Issue by Zediax** [Medacorp/Luigi-s-Mansion#76]
**Describe the bug**
The map map (ridiculous description i know) does not show if the rooms are visited, cleared or not. It does that on the 3rd floor and the fortune-telling room.

**Expected behavior**
Seen and cleared rooms should hae their color shown.

**Map version:**
 Still 2.2

**Additional context**
I just realized that (the map shows only gray rooms on the 3rd floor and the basement and a light gray room on the fortune-telling room and the light switch room) I did all these rooms already but the map just don't shows that :/

**Screenshots**
![2022-08-31_19 02 46](https://user-images.githubusercontent.com/112496276/187737751-f0198a41-573d-4565-a013-017b5c91bc0e.png)
![2022-08-31_19 02 32](https://user-images.githubusercontent.com/112496276/187737756-761b2d56-6040-4b68-a17c-fec38d0b799d.png)
![2022-08-31_19 02 27](https://user-images.githubusercontent.com/112496276/187737759-3f4e2532-a651-4850-983e-27288f81e441.png)

**Comment by Dhranios** [comment]
How did the map get opened? Just the usual way via GBH menu/double use?

The map area only updates if no player was looking at the map, and the map gets opened, or if the map is opened by a player and a room/door status changes.

**Comment by Zediax** [comment]
i opened the map the usual way of course and yeah my game crashed while i was on the map screen

**Comment by Zediax** [comment]
and i don't think the map didn't saved the chuckns since i regularly check the map so i know where i can go/have things to do but without the color display doing that is unpraticable

**Comment by Dhranios** [comment]
Then the crash explains it, and there's nothing I can do to fix the map, as it's quite literally the game just not saving block changes.
Simply re-opening it will correct it.

Trust me, game crashes can revert chunks to really old states if the world wasn't forcibly saved in the meantime.

**Comment by Dhranios** [comment]
I will write up a little fix for the player heads being in the inventory though. :)

**Comment by Zediax** [comment]
also each time i exit the map screen i get a head of myself

**Comment by Zediax** [comment]
re-entring the map does nothing tho
:/

**Comment by Dhranios** [comment]
Hmm, could you send the data/command_storage_luigis_mansion.dat file?

**Comment by Zediax** [comment]
yeah sure

**Comment by Zediax** [comment]
wait it seems that i don't have that file ?

**Comment by Zediax** [comment]
really weird

**Comment by Zediax** [comment]
nvm i do

**Comment by Zediax** [comment]
i'll upload it on mega again since github doesn't accept it -_-

**Comment by Dhranios** [comment]
I couldn't download from MEGA last time, so I'd prefer if you put it on another site, EG, google drive

**Comment by Zediax** [comment]
oh
okay then google drive

**Comment by Zediax** [comment]
https://drive.google.com/file/d/1hd39G9D7AV-c5i5BGZnG2Icso0E02DuP/view?usp=sharing

here

**Comment by Zediax** [comment]
hope it works this time

**Comment by Dhranios** [comment]
Yeah, that works

**Comment by Dhranios** [comment]
hmm, the map data appears to be fine...

Could you tell me if you have the "cancel" tag? (`/tag @s remove ` (space included), see if it is suggested)

Run the following command to force the map to update: `function luigis_mansion:items/gameboy_horror/map/display/normal/generate`

**Comment by Zediax** [comment]
i don't have the "cancel" tag

**Comment by Zediax** [comment]
do i run that command while being on the map screen ?

**Comment by Dhranios** [comment]
If you close the map, do you have the "looking_at_map" tag? (If not, I have no idea what causes your issue)

Yes.

**Comment by Zediax** [comment]
i don't have it sadly i'll do the command right away

**Comment by Zediax** [comment]
okay it worked thanks
