### ISSUE TITLE
Mod issue: [Lunar Client] models not loading in

### ISSUE THREAD

**Issue by techteen3000** [Medacorp/Luigi-s-Mansion#98]
**Describe the bug**
Items on armor stand vanish (armor stand still exists).

**To Reproduce**
1. Go to the mansion
2. Open the door
3. The doors inside aren't visible

**Expected behavior**
Doors are visible

**Map version:**
2.3.7
**Enabled add-ons**
N/A

**Additional context**
Caused by Lunar Client (https://support.lunarclient.com/support/tickets/148699)

**Comment by techteen3000** [comment]
nvm it was cause of me running lunar solved

**Comment by Dhranios** [comment]
Reopening, while a lunar issue, I'll try to see what I can do to fix it on my part

**Comment by techteen3000** [comment]
adding to this models are invis they are still there just not visable

**Comment by Dhranios** [comment]
Unfixable on my part, no armor stands are shown to the client at all, regardless of NBT.
Lunar must fix this on their end, I can't do anything to resolve this.

**Comment by Dhranios** [comment]
Marked as cleared by the lunar team, should be resolved on lunar's next update.
